spring:
  datasource:
    url: jdbc:mysql://arn:aws:iam::305476115814:user/petfeast-backend:3306/petfeast
    username: 
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

cloud:
  aws:
    region:
      static: ap-south-1
    credentials:
      access-key:
      secret-key:
